### ISSUE TITLE
The chrome extension link doesn't work

### ISSUE THREAD

**Issue by vadykoo** [algolia/github-awesome-autocomplete#101]
Where I can download the extension?

https://chrome.google.com/webstore/detail/awesome-autocomplete-for/djkfdjpoelphhdclfjhnffmnlnoknfnd?hl=uk

**Comment by redox** [comment]
hey @vadykoo, the chrome extension has been recently removed from the chromestore because we didn't take the time to update a few new requirements they ask all their extensions to follow.

Until we fix this (not in the near future unfortunately), I would recommend you build the sources and add the extension from [the chrome folder it will generate](https://github.com/algolia/github-awesome-autocomplete#installation-1).

**Comment by vadykoo** [comment]
@redox ok, thank you
