### ISSUE TITLE
Could one use this same search in a webpage?

### ISSUE THREAD

**Issue by theiliad** [algolia/github-awesome-autocomplete#57]
I'm not too familiar with Algolia's **instantsearch.js**, but would I be able to make this same autocomplete for Github say in a React webapp?

**Comment by theiliad** [comment]
Just the **Top Repositories** and the **Last Active Users** section would be good enough...

**Comment by Haroenv** [comment]
Sure, as a community project, we'd love to find new usages for this data. 

```js
appID = TLCDTR8BIO
apiKey = 686cce2f5dd3c38130b303e1c842c3e3
```

There's a `top_1m_repos` index, `last_1m_users`, `users` and `repositories`. 

If you're using React, feel free to read the documentation at [the website](https://community.algolia.com/react-instantsearch/)

Because this is provided for free, please add a "powered by Algolia" using for example the [`<PoweredBy />`](https://community.algolia.com/react-instantsearch/widgets/PoweredBy.html) component. 

Oh, and I'm also super curious what you're building, so it would be really cool to read about it on [our forum](https://discourse.algolia.com) or somewhere else.

**Comment by theiliad** [comment]
@Haroenv Just tried this, although this is the first time I'm using Aloglia, it was super easy to get it working 😍

**Comment by Haroenv** [comment]
Awesome, looking forward to what you built 🔥
